title: "AI Skills Journey"
description: "Learn practical ChatGPT skills — from your first prompt to real-world applications"
author: "Justin Klutka"
theme: minima
baseurl: "/ai-upskilling-series"
url: "https://jklutka.github.io"
github_username: jklutka
show_excerpts: true